### ISSUE TITLE
Maven HPI Plugin is invoked without Upper Bounds Check

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/custom-war-packager#8]
When a Custom WAR is packaged by invoking Maven HPI plugin, the intermediate POM has no upper bounds checks. So the resulting WAR may compile but then fail to start depending on the inclusion order.

```
Mar 28, 2018 2:48:42 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Artifact Manager on S3 plugin v256.0-master-bc845780854b6a522f6a07a63f24fe2c21a739bc-SNAPSHOT (private-bc845780-nenashev) (artifact-manager-s3)
java.io.IOException: Artifact Manager on S3 plugin v256.0-master-bc845780854b6a522f6a07a63f24fe2c21a739bc-SNAPSHOT (private-bc845780-nenashev) failed to load.
 - Structs Plugin v1.7 is older than required. To fix, install v1.10 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:514)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1062)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by obv-mikhail** [comment]
@oleg-nenashev Is making a Jenkins war prepackaged with Blue Ocean impossible due to this bug or does there exist some work around?

**Comment by obv-mikhail** [comment]
@oleg-nenashev Ok, thanks!
